set(CPACK_GENERATOR "DEB")
set(CPACK_PACKAGE_NAME "kbextract")
set(CPACK_PACKAGE_VENDOR "314r")
set(CPACK_PACKAGE_CONTACT "contact.314r@gmail.com")
if(NOT DEFINED CPACK_PACKAGE_VERSION)
    set(CPACK_PACKAGE_VERSION "0.1.0")
endif()
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Browse and copy highlights and notes from Kobo eReaders")
set(CPACK_PACKAGE_DESCRIPTION
    "kbextract is a desktop application for browsing highlights and notes stored on a connected Kobo eReader and copying them for use elsewhere.")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/314r/kbextract")
if(NOT DEFINED CPACK_PACKAGE_FILE_NAME)
    set(CPACK_PACKAGE_FILE_NAME "kbextract-${CPACK_PACKAGE_VERSION}-linux-x86_64")
endif()
set(CPACK_PACKAGING_INSTALL_PREFIX "/")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "314r <contact.314r@gmail.com>")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
set(CPACK_DEBIAN_PACKAGE_SECTION "utils")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION TRUE)
